create extension if not exists "pgcrypto";

create table if not exists public.outlook_exchange_sync_queue (
  id uuid primary key default gen_random_uuid(),
  action text not null check (
    action in (
      'create_contact',
      'update_contact',
      'delete_contact',
      'create_group',
      'update_group',
      'delete_group',
      'update_group_members',
      'full_sync'
    )
  ),
  entity_type text not null check (
    entity_type in ('contact', 'group', 'group_members', 'full_sync')
  ),
  entity_id text,
  entity_email text,
  entity_alias text,
  display_name text,
  payload jsonb not null default '{}'::jsonb,
  event_id uuid not null default gen_random_uuid(),
  change_set_id uuid,
  change_set_ids uuid[] not null default array[]::uuid[],
  audit_log_id uuid references public.audit_logs(id) on delete set null,
  audit_log_ids uuid[] not null default array[]::uuid[],
  actor_id text,
  entity_key text not null default ('legacy:' || gen_random_uuid()::text),
  changed_fields text[] not null default array[]::text[],
  source_version timestamptz,
  status text not null default 'pending' check (
    status in ('pending', 'processing', 'completed', 'failed', 'skipped')
  ),
  attempts integer not null default 0,
  requested_by text,
  error_message text,
  error_history jsonb not null default '[]'::jsonb,
  exchange_verified_at timestamptz,
  processing_started_at timestamptz,
  claimed_at timestamptz,
  next_attempt_at timestamptz,
  run_id uuid,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  enqueued_at timestamptz not null default clock_timestamp(),
  queue_sequence bigint generated by default as identity,
  constraint outlook_exchange_sync_queue_error_history_array
    check (jsonb_typeof(error_history) = 'array')
);

create index if not exists outlook_exchange_sync_queue_status_idx
on public.outlook_exchange_sync_queue(status, created_at);

create index if not exists outlook_exchange_sync_queue_entity_idx
on public.outlook_exchange_sync_queue(entity_type, entity_id, created_at desc);

create index if not exists outlook_exchange_sync_queue_email_idx
on public.outlook_exchange_sync_queue(entity_email)
where entity_email is not null;

create index if not exists outlook_exchange_sync_queue_alias_idx
on public.outlook_exchange_sync_queue(entity_alias)
where entity_alias is not null;

create unique index if not exists outlook_exchange_sync_queue_event_id_idx
on public.outlook_exchange_sync_queue(event_id);

create index if not exists outlook_exchange_sync_queue_retry_idx
on public.outlook_exchange_sync_queue(status, next_attempt_at, queue_sequence);

create index if not exists outlook_exchange_sync_queue_entity_key_idx
on public.outlook_exchange_sync_queue(entity_key, status, queue_sequence);

create index if not exists outlook_exchange_sync_queue_run_idx
on public.outlook_exchange_sync_queue(run_id)
where run_id is not null;

create index if not exists outlook_exchange_sync_queue_audit_log_id_idx
on public.outlook_exchange_sync_queue(audit_log_id)
where audit_log_id is not null;

alter table public.outlook_exchange_sync_queue enable row level security;

drop policy if exists "outlook_exchange_sync_queue_read" on public.outlook_exchange_sync_queue;
drop policy if exists "outlook_exchange_sync_queue_write" on public.outlook_exchange_sync_queue;

revoke select, insert, update, delete on public.outlook_exchange_sync_queue from anon, authenticated;

create table if not exists public.outlook_exchange_sync_certifications (
  run_id uuid primary key,
  sync_mode text not null,
  queue_high_water_sequence bigint not null,
  queue_high_water_updated_at timestamptz,
  source_fingerprint text not null,
  certified_at timestamptz not null,
  result jsonb not null,
  created_at timestamptz not null default clock_timestamp(),
  constraint outlook_exchange_sync_certifications_full_mode
    check (sync_mode = 'full'),
  constraint outlook_exchange_sync_certifications_result_object
    check (jsonb_typeof(result) = 'object')
);

comment on table public.outlook_exchange_sync_certifications is
  'Protected durable receipts for source-fenced full Exchange certifications and lost-response replay.';
comment on column public.outlook_exchange_sync_certifications.run_id is
  'Unique certification identity; reusing a run ID with a different fence or fingerprint is rejected.';
comment on column public.outlook_exchange_sync_certifications.result is
  'Original successful RPC result returned verbatim, with idempotent=true added on replay.';

alter table public.outlook_exchange_sync_certifications enable row level security;
revoke all on public.outlook_exchange_sync_certifications from public, anon, authenticated;

create table if not exists public.outlook_exchange_sync_lock (
  lock_name text primary key,
  run_id uuid not null,
  sync_mode text not null,
  acquired_at timestamptz not null,
  heartbeat_at timestamptz not null,
  expires_at timestamptz not null
);

alter table public.outlook_exchange_sync_lock enable row level security;
revoke all on public.outlook_exchange_sync_lock from public, anon, authenticated;

-- Queue triggers, audit correlation, claim/lease RPCs, and base retry semantics
-- are installed by migration 20260722040617_exchange_sync_transactional_outbox.sql.
-- Expired-lease terminalization, append-only retry/error history, conservative
-- contact plus field-scoped group/member UPDATE triggers, atomic verified
-- completion/supersession, and the
-- source-fenced full-certification sweep are installed by migration
-- 20260722064345_harden_exchange_queue_stale_claims.sql.
