/* Run with node tests/task-calendar.browser.test.cjs.
 * Playwright may be supplied through NODE_PATH. This bundles the real page and
 * permission guard; all requests use synthetic in-memory data. No live emails,
 * calendars, authentication sessions, or personal browser windows are touched.
 */
const assert = require("node:assert/strict")
const http = require("node:http")
const path = require("node:path")
const { build } = require("esbuild")

const root = path.resolve(__dirname, "..")
const row = (page, name) => page.locator("tbody tr").filter({ hasText: name })
const selectedRows = (page) => page.locator('tbody tr[aria-selected="true"]')
const button = (page, name) => page.getByRole("button", { name, exact: true })
const writes = (page) => page.evaluate(() => window.__taskCalendarHarness.requests.filter((request) => request.method !== "GET"))

async function main() {
  const mocks = path.join(root, "tests/fixtures/task-calendar-mocks.ts")
  const bundle = await build({
    absWorkingDir: root, entryPoints: ["tests/fixtures/task-calendar.tsx"], bundle: true,
    write: false, outdir: "task-calendar-browser-fixture", platform: "browser", format: "iife", jsx: "automatic", logLevel: "warning",
    define: { "process.env.NODE_ENV": '"development"' },
    plugins: [{ name: "synthetic-task-boundaries", setup(builder) {
      builder.onResolve({ filter: /^@\/lib\/useSimpleAdminAuth$|^next\/navigation$/ }, () => ({ path: mocks }))
    } }],
  })
  const assets = new Map(bundle.outputFiles.map((file) => [`/${path.basename(file.path)}`, file.contents]))
  const script = [...assets.keys()].find((name) => name.endsWith(".js"))
  const html = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Synthetic Task Calendar regression</title><style>
    :root { --fc-admin-page-bg:#f4f5f8; --fc-admin-font:Arial,sans-serif; --fc-admin-panel-text:#20232a; --fc-admin-panel-bg:#fff; --fc-admin-panel-soft-bg:#f8f9fc; --fc-admin-selected-bg:#e8f2ff; --fc-admin-selected-text:#004c99; --fc-admin-selected-border:#8ab4f8; --fc-admin-border:#ccd0d8; --fc-admin-border-soft:#dfe2e8; --fc-admin-muted:#69707d; --fc-admin-button-bg:#f4f5f8; --fc-admin-button-text:#20232a; --fc-admin-button-border:#ccd0d8; --fc-admin-primary-button-bg:#0672ed; --fc-admin-primary-button-text:#fff; --fc-admin-danger-bg:#dc001b; --fc-admin-danger-text:#fff; --fc-admin-danger-border:#dc001b; --fc-admin-link:#0066cc; --fc-tool-input-bg:#fff; --fc-row-bg:#f5f5f7; --fc-table-head-bg:#f5f5f7; --fc-table-head-text:#20232a; }
    * { box-sizing:border-box; } body { margin:0; font-family:Arial,sans-serif; } button,input,select { font:inherit; } button:disabled { opacity:.55; }
  </style></head><body><div id="root"></div><script src="${script}"></script></body></html>`
  const server = http.createServer((request, response) => {
    if (request.method !== "GET") { response.writeHead(405); response.end("Read-only fixture server"); return }
    const asset = assets.get(new URL(request.url, "http://127.0.0.1").pathname)
    response.setHeader("Content-Type", asset ? "text/javascript" : "text/html")
    response.end(asset || html)
  })
  await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve))
  const baseUrl = `http://127.0.0.1:${server.address().port}`
  let browser
  try {
    const { chromium } = require("playwright")
    browser = await chromium.launch({ headless: true, ...(process.env.CHROME_EXECUTABLE_PATH ? { executablePath: process.env.CHROME_EXECUTABLE_PATH } : {}) })
    const context = await browser.newContext({ viewport: { width: 1400, height: 900 } })
    const blocked = [], errors = []
    await context.route("**/*", (route) => {
      if (new URL(route.request().url()).origin === baseUrl) return route.continue()
      blocked.push(route.request().url())
      return route.abort()
    })
    const page = await context.newPage()
    page.setDefaultTimeout(8000)
    page.on("pageerror", (error) => errors.push(error.message))
    page.on("console", (message) => { if (message.type() === "error") errors.push(message.text()) })
    async function reset(access = "edit", empty = false) {
      await page.goto(`${baseUrl}?access=${access}&empty=${empty ? "1" : "0"}`)
      if (empty) await page.getByText("No scheduled tasks.", { exact: true }).waitFor()
      else await row(page, "FIRST SYNTHETIC TASK").waitFor()
      // Observe past the former 700ms autosave to prove loading is read-only.
      await page.waitForTimeout(900)
    }
    await reset()
    const initialWrites = await writes(page)
    assert.deepEqual(initialWrites, [], "loading never writes the task calendar")
    assert.equal(await selectedRows(page).count(), 0)
    const first = row(page, "FIRST SYNTHETIC TASK")
    await first.locator("td").first().click()
    assert.equal(await selectedRows(page).count(), 1)
    assert.equal(await first.getAttribute("aria-selected"), "true")
    assert.equal(await page.getByRole("heading", { name: "Edit Task" }).count(), 0, "single click does not open editing")
    assert.equal(await first.evaluate((node) => getComputedStyle(node).backgroundColor), "rgb(232, 242, 255)")
    assert.notEqual(await first.evaluate((node) => getComputedStyle(node).boxShadow), "none", "selected row has a non-colour-only outline")
    await button(page, "OL").click()
    assert.equal(await first.getAttribute("aria-selected"), "true", "person highlighting cannot clear row selection")
    await button(page, "Clear").click()
    assert.equal(await first.getAttribute("aria-selected"), "true")
    await row(page, "SECOND SYNTHETIC TASK").locator("td").last().click()
    assert.equal(await first.getAttribute("aria-selected"), "false")
    assert.equal(await selectedRows(page).count(), 1)
    const third = row(page, "THIRD SYNTHETIC TASK")
    await third.focus()
    await page.keyboard.press("Space")
    assert.equal(await third.getAttribute("aria-selected"), "true")
    await page.keyboard.press("Enter")
    assert.equal(await page.getByRole("heading", { name: "Edit Task" }).count(), 0)
    await first.focus()
    await page.keyboard.press("Tab")
    assert.equal(await row(page, "SECOND SYNTHETIC TASK").evaluate((node) => node === document.activeElement), true)
    await page.waitForTimeout(900)
    assert.deepEqual(await writes(page), initialWrites, "row and person selection must never save calendar data")
    console.log("PASS: entire-row click, one selected row, independent person highlight, keyboard selection, no writes")

    await first.dblclick()
    await page.getByRole("heading", { name: "Edit Task" }).waitFor()
    await page.getByLabel("Task", { exact: true }).fill("RENAMED SYNTHETIC TASK")
    await button(page, "Save").click()
    const renamed = row(page, "RENAMED SYNTHETIC TASK")
    await renamed.waitFor()
    assert.equal(await renamed.getAttribute("aria-selected"), "true", "selection follows stable ID through an edit")
    await page.waitForFunction(() => window.__taskCalendarHarness.tasks[0].task === "RENAMED SYNTHETIC TASK")
    assert.equal((await writes(page)).length, initialWrites.length + 1)
    await renamed.dblclick()
    await page.getByLabel("Task", { exact: true }).fill("CANCELED NAME")
    page.once("dialog", (prompt) => prompt.accept())
    await button(page, "Cancel").click()
    assert.equal(await renamed.getAttribute("aria-selected"), "true")
    assert.equal(await row(page, "CANCELED NAME").count(), 0)
    console.log("PASS: double-click editing, save/cancel, stable selected task after re-render")

    await reset()
    await row(page, "FIRST SYNTHETIC TASK").dblclick()
    const modal = page.getByRole("dialog", { name: "Edit Task", exact: true })
    await modal.getByLabel("Task", { exact: true }).fill("RETRY THIS TASK")
    await page.evaluate(() => { window.__taskCalendarHarness.deferNext = true; window.__taskCalendarHarness.failNext = true })
    await button(page, "Save").click()
    await page.waitForFunction(() => Boolean(window.__taskCalendarHarness.releaseWrite))
    assert.equal(await modal.getAttribute("aria-busy"), "true")
    assert.equal(await button(page, "Cancel").isDisabled(), true)
    assert.equal(await button(page, "Delete").isDisabled(), true)
    await page.keyboard.press("Escape")
    assert.equal(await modal.isVisible(), true, "pending save cannot be closed or canceled")
    await page.evaluate(() => window.__taskCalendarHarness.releaseWrite())
    await page.getByRole("alert").filter({ hasText: "Synthetic save failure" }).waitFor()
    assert.equal(await modal.getByLabel("Task", { exact: true }).inputValue(), "RETRY THIS TASK")
    assert.equal(await row(page, "FIRST SYNTHETIC TASK").count(), 1, "failed save does not change the committed table")
    await button(page, "Save").click()
    await modal.waitFor({ state: "hidden" })
    assert.equal(await row(page, "RETRY THIS TASK").count(), 1)
    assert.equal((await writes(page)).length, 2)
    console.log("PASS: confirmed async save, in-flight locking, retained failed draft, explicit retry")

    await reset()
    await row(page, "FIRST SYNTHETIC TASK").dblclick()
    await modal.getByLabel("Task", { exact: true }).fill("STALE TASK DRAFT")
    await page.evaluate(() => { window.__taskCalendarHarness.conflictNext = true })
    await button(page, "Save").click()
    await page.getByRole("alert").filter({ hasText: "This task changed" }).waitFor()
    assert.equal(await modal.getByLabel("Task", { exact: true }).inputValue(), "STALE TASK DRAFT")
    assert.equal(await row(page, "OTHER USER SAVED TASK").count(), 1)
    await button(page, "Save").click()
    assert.equal(await row(page, "OTHER USER SAVED TASK").count(), 1, "repeated stale save never updates its base version")
    page.once("dialog", (prompt) => prompt.accept())
    await button(page, "Cancel").click()
    await row(page, "OTHER USER SAVED TASK").dblclick()
    await modal.getByLabel("Task", { exact: true }).fill("REOPENED TASK DRAFT")
    await button(page, "Save").click()
    await modal.waitFor({ state: "hidden" })
    assert.equal(await row(page, "REOPENED TASK DRAFT").count(), 1)
    console.log("PASS: conflict refreshes table, retains stale draft, and requires reopening latest task")

    await reset()
    await button(page, "Add New Task").click()
    const newModal = page.getByRole("dialog", { name: "New Task", exact: true })
    await newModal.getByLabel("Task", { exact: true }).fill("VALIDATED NEW TASK")
    await newModal.getByRole("button", { name: "Weekly", exact: true }).click()
    await button(page, "Save").click()
    await page.getByRole("alert").filter({ hasText: "Choose a weekday" }).waitFor()
    assert.deepEqual(await writes(page), [])
    await newModal.getByRole("button", { name: "Sun", exact: true }).click()
    await button(page, "Save").click()
    await page.getByRole("alert").filter({ hasText: "Notify To" }).waitFor()
    await newModal.getByRole("button", { name: "DT", exact: true }).first().click()
    await newModal.getByRole("button", { name: "Yearly", exact: true }).click()
    await button(page, "Save").click()
    await page.getByRole("alert").filter({ hasText: "Choose at least one month" }).waitFor()
    await newModal.getByRole("button", { name: "Feb", exact: true }).click()
    await newModal.getByLabel("Day Of Month", { exact: true }).fill("1, 32, wrong")
    await button(page, "Save").click()
    await page.getByRole("alert").filter({ hasText: "Enter days from 1 to 31" }).waitFor()
    assert.deepEqual(await writes(page), [])
    await newModal.getByLabel("Day Of Month", { exact: true }).fill("28, 29")
    await button(page, "Save").click()
    await newModal.waitFor({ state: "hidden" })
    const added = row(page, "VALIDATED NEW TASK")
    await added.dblclick()
    await modal.waitFor()
    page.once("dialog", (prompt) => prompt.accept())
    await button(page, "Delete").click()
    await modal.waitFor({ state: "hidden" })
    assert.equal(await added.count(), 0)
    assert.equal((await writes(page)).length, 2)
    console.log("PASS: recurrence and recipient validation, dynamic staff buttons, confirmed create/delete")

    await reset("edit", true)
    assert.equal(await page.locator("tbody tr").count(), 0, "authoritative empty list never resurrects bundled tasks")
    assert.deepEqual(await writes(page), [])
    console.log("PASS: empty calendar is authoritative and read-only on load")

    await reset("view")
    assert.equal(await button(page, "Add New Task").isDisabled(), true, "real View-only guard remains enabled")
    assert.deepEqual(await writes(page), [], "View-only requests never reach the API")
    await row(page, "SECOND SYNTHETIC TASK").locator("td").first().click()
    assert.equal(await row(page, "SECOND SYNTHETIC TASK").getAttribute("aria-selected"), "true")
    await row(page, "THIRD SYNTHETIC TASK").focus()
    await page.keyboard.press("Space")
    assert.equal(await row(page, "THIRD SYNTHETIC TASK").getAttribute("aria-selected"), "true")
    await page.waitForTimeout(900)
    assert.deepEqual(await writes(page), [])
    console.log("PASS: View-only users can select rows without any new editing permission or write")

    await page.setViewportSize({ width: 390, height: 844 })
    const scroller = page.locator("table").locator("..");
    await scroller.evaluate((node) => { node.scrollLeft = node.scrollWidth })
    await row(page, "FIRST SYNTHETIC TASK").locator("td").last().click()
    assert.equal(await row(page, "FIRST SYNTHETIC TASK").getAttribute("aria-selected"), "true")
    assert.equal(await row(page, "FIRST SYNTHETIC TASK").evaluate((node) => getComputedStyle(node).backgroundColor), "rgb(232, 242, 255)")
    assert.equal(await selectedRows(page).count(), 1)
    assert.deepEqual(errors, [])
    assert.deepEqual(blocked, [])
    console.log("PASS: selection remains usable after horizontal scrolling on mobile; no external requests or browser errors")
  } finally {
    if (browser) await browser.close()
    await new Promise((resolve) => server.close(resolve))
  }
}

main().catch((error) => { console.error(error); process.exitCode = 1 })
