create table if not exists public.openai_usage_events (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  page_id text not null,
  page_path text not null,
  feature text not null,
  api_endpoint text not null default 'responses',
  model text not null default '',
  request_id text not null default '',
  status text not null check (status in ('success', 'error')),
  http_status integer not null default 0,
  input_tokens bigint not null default 0 check (input_tokens >= 0),
  cached_input_tokens bigint not null default 0 check (cached_input_tokens >= 0),
  output_tokens bigint not null default 0 check (output_tokens >= 0),
  reasoning_tokens bigint not null default 0 check (reasoning_tokens >= 0),
  total_tokens bigint not null default 0 check (total_tokens >= 0),
  web_search_calls integer not null default 0 check (web_search_calls >= 0),
  duration_ms integer not null default 0 check (duration_ms >= 0),
  app_commit text not null default ''
);

create index if not exists openai_usage_events_occurred_at_idx
  on public.openai_usage_events (occurred_at desc);

create index if not exists openai_usage_events_page_occurred_idx
  on public.openai_usage_events (page_id, occurred_at desc);

alter table public.openai_usage_events enable row level security;
revoke all on table public.openai_usage_events from anon, authenticated;
grant select, insert on table public.openai_usage_events to service_role;
grant usage, select on sequence public.openai_usage_events_id_seq to service_role;
