alter table public.outlook_exchange_sync_queue
  add column if not exists event_id uuid not null default gen_random_uuid(),
  add column if not exists change_set_id uuid,
  add column if not exists change_set_ids uuid[] not null default array[]::uuid[],
  add column if not exists audit_log_id uuid references public.audit_logs(id) on delete set null,
  add column if not exists audit_log_ids uuid[] not null default array[]::uuid[],
  add column if not exists actor_id text,
  add column if not exists entity_key text,
  add column if not exists changed_fields text[] not null default array[]::text[],
  add column if not exists source_version timestamptz,
  add column if not exists run_id uuid,
  add column if not exists claimed_at timestamptz,
  add column if not exists next_attempt_at timestamptz,
  add column if not exists enqueued_at timestamptz not null default clock_timestamp(),
  add column if not exists queue_sequence bigint generated by default as identity;

update public.outlook_exchange_sync_queue as queue
set entity_key = case
  when queue.entity_type = 'group_members' then concat_ws(
    ':',
    queue.entity_type,
    coalesce(nullif(queue.entity_id, ''), 'unknown-group'),
    coalesce(
      nullif(queue.payload #>> '{beforeMember,contact_id}', ''),
      nullif(queue.payload #>> '{afterMember,contact_id}', ''),
      nullif(queue.payload #>> '{addedContact,SourceContactId}', ''),
      nullif(queue.payload #>> '{removedContact,SourceContactId}', ''),
      queue.id::text
    )
  )
  else concat_ws(
    ':',
    queue.entity_type,
    coalesce(
      nullif(queue.entity_id, ''),
      nullif(lower(queue.entity_email), ''),
      nullif(lower(queue.entity_alias), ''),
      queue.id::text
    )
  )
end
where queue.entity_key is null or queue.entity_key = '';

alter table public.outlook_exchange_sync_queue
  alter column entity_key set default ('legacy:' || gen_random_uuid()::text),
  alter column entity_key set not null;

create unique index if not exists outlook_exchange_sync_queue_event_id_idx
  on public.outlook_exchange_sync_queue(event_id);

create index if not exists outlook_exchange_sync_queue_retry_idx
  on public.outlook_exchange_sync_queue(status, next_attempt_at, queue_sequence);

create index if not exists outlook_exchange_sync_queue_entity_key_idx
  on public.outlook_exchange_sync_queue(entity_key, status, queue_sequence);

create index if not exists outlook_exchange_sync_queue_run_idx
  on public.outlook_exchange_sync_queue(run_id)
  where run_id is not null;

create or replace function public.audit_table_changes()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  before_payload jsonb;
  after_payload jsonb;
  changed text[];
  actor_id text;
  actor_name text;
  actor_source text;
  context_payload jsonb;
  undo_of uuid;
  correlation_id uuid;
begin
  if tg_table_schema = 'public' and tg_table_name = 'audit_logs' then
    if tg_op = 'DELETE' then return old; end if;
    return new;
  end if;

  before_payload := case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end;
  after_payload := case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end;

  if tg_op = 'UPDATE' then
    changed := array_remove(public.audit_changed_fields(before_payload, after_payload), 'updated_at');
    if coalesce(array_length(changed, 1), 0) = 0 then return new; end if;
    if tg_table_name = 'shared_addressbook_groups'
      and changed <@ array['member_count']::text[]
    then
      return new;
    end if;
  else
    changed := array[]::text[];
  end if;

  if tg_table_name = 'office_calendar_store'
    and coalesce(coalesce(after_payload, before_payload) ->> 'key', '')
      not in ('event-calendar', 'task-calendar')
  then
    if tg_op = 'DELETE' then return old; end if;
    return new;
  end if;

  actor_id := coalesce(
    nullif(public.audit_text_setting('app.audit_actor_id'), ''),
    nullif(public.audit_request_header('x-bunker-admin-user'), '')
  );

  if actor_id is null then
    if tg_op = 'DELETE' then return old; end if;
    return new;
  end if;

  actor_name := coalesce(
    nullif(public.audit_text_setting('app.audit_actor_name'), ''),
    nullif(public.audit_request_header('x-bunker-admin-display-name'), ''),
    actor_id
  );
  actor_source := case
    when nullif(public.audit_text_setting('app.audit_actor_id'), '') is not null then 'app'
    else 'header'
  end;

  correlation_id := public.audit_uuid_setting('app.audit_correlation_id');
  if correlation_id is null then
    correlation_id := gen_random_uuid();
    perform set_config('app.audit_correlation_id', correlation_id::text, true);
  end if;

  context_payload := coalesce(
    public.audit_json_setting('app.audit_context'),
    '{}'::jsonb
  ) || jsonb_strip_nulls(jsonb_build_object(
    'pageId', nullif(public.audit_request_header('x-bunker-admin-page-id'), ''),
    'pageLabel', nullif(public.audit_request_header('x-bunker-admin-page-label'), ''),
    'pagePath', nullif(public.audit_request_header('x-bunker-admin-page-path'), ''),
    'correlationId', correlation_id
  ));
  undo_of := public.audit_uuid_setting('app.audit_undo_of_log_id');

  insert into public.audit_logs (
    actor_id,
    actor_name,
    actor_source,
    table_schema,
    table_name,
    operation,
    record_pk,
    changed_fields,
    before_row,
    after_row,
    request_context,
    undo_of_log_id
  ) values (
    actor_id,
    actor_name,
    actor_source,
    tg_table_schema,
    tg_table_name,
    tg_op,
    public.audit_row_pk(tg_table_schema, tg_table_name, coalesce(after_payload, before_payload)),
    changed,
    before_payload,
    after_payload,
    context_payload,
    undo_of
  );

  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

create or replace function public.outlook_exchange_alias(
  p_value text,
  p_fallback text
)
returns text
language sql
immutable
set search_path = ''
as $$
  select coalesce(
    nullif(
      left(
        regexp_replace(
          regexp_replace(
            lower(regexp_replace(coalesce(nullif(btrim(p_value), ''), p_fallback), '&', ' and ', 'g')),
            '[^a-z0-9._-]+',
            '-',
            'g'
          ),
          '^[.-]+|[.-]+$',
          '',
          'g'
        ),
        58
      ),
      ''
    ),
    p_fallback
  );
$$;

create or replace function public.outlook_exchange_queue_source_change()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  before_payload jsonb;
  after_payload jsonb;
  earliest_before jsonb;
  changed text[];
  audit_actor_id_value text;
  actor_id_value text;
  actor_name_value text;
  action_value text;
  entity_type_value text;
  entity_id_value text;
  entity_key_value text;
  entity_email_value text;
  entity_alias_value text;
  display_name_value text;
  source_version_value timestamptz;
  payload_value jsonb;
  before_key text;
  after_key text;
  audit_log_id_value uuid;
  audit_log_ids_value uuid[];
  change_set_id_value uuid;
  change_set_ids_value uuid[];
  group_row public.shared_addressbook_groups%rowtype;
  contact_row public.shared_addressbook_contacts%rowtype;
  pending_queue public.outlook_exchange_sync_queue%rowtype;
  operation_history jsonb;
begin
  before_payload := case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end;
  after_payload := case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end;
  changed := case
    when tg_op = 'UPDATE' then array_remove(public.audit_changed_fields(before_payload, after_payload), 'updated_at')
    else array[]::text[]
  end;

  if tg_op = 'UPDATE' and coalesce(array_length(changed, 1), 0) = 0 then
    return new;
  end if;
  if tg_table_name = 'shared_addressbook_groups'
    and tg_op = 'UPDATE'
    and changed <@ array['member_count']::text[]
  then
    return new;
  end if;

  audit_actor_id_value := coalesce(
    nullif(public.audit_text_setting('app.audit_actor_id'), ''),
    nullif(public.audit_request_header('x-bunker-admin-user'), '')
  );
  if audit_actor_id_value is null or lower(audit_actor_id_value) = 'unknown' then
    raise exception 'Address book changes require an authenticated audit actor.';
  end if;
  actor_id_value := audit_actor_id_value;
  actor_name_value := coalesce(
    nullif(public.audit_text_setting('app.audit_actor_name'), ''),
    nullif(public.audit_request_header('x-bunker-admin-display-name'), ''),
    actor_id_value
  );
  change_set_id_value := public.audit_uuid_setting('app.audit_correlation_id');

  if tg_table_name = 'shared_addressbook_contacts' then
    before_key := 'beforeContact';
    after_key := 'afterContact';
    action_value := case tg_op
      when 'INSERT' then 'create_contact'
      when 'DELETE' then 'delete_contact'
      else 'update_contact'
    end;
    entity_type_value := 'contact';
    entity_id_value := coalesce(after_payload->>'id', before_payload->>'id');
    entity_key_value := 'contact:' || entity_id_value;
    entity_email_value := lower(nullif(btrim(coalesce(after_payload->>'primary_email', before_payload->>'primary_email')), ''));
    display_name_value := nullif(btrim(coalesce(after_payload->>'display_name', before_payload->>'display_name')), '');
    entity_alias_value := public.outlook_exchange_alias(
      coalesce(
        nullif(after_payload->>'nickname', ''),
        nullif(after_payload->>'display_name', ''),
        nullif(before_payload->>'nickname', ''),
        nullif(before_payload->>'display_name', '')
      ),
      'contact-' || entity_id_value
    );
  elsif tg_table_name = 'shared_addressbook_groups' then
    before_key := 'beforeGroup';
    after_key := 'afterGroup';
    action_value := case tg_op
      when 'INSERT' then 'create_group'
      when 'DELETE' then 'delete_group'
      else 'update_group'
    end;
    entity_type_value := 'group';
    entity_id_value := coalesce(after_payload->>'id', before_payload->>'id');
    entity_key_value := 'group:' || entity_id_value;
    display_name_value := nullif(btrim(coalesce(after_payload->>'name', before_payload->>'name')), '');
    entity_alias_value := public.outlook_exchange_alias(
      coalesce(
        nullif(after_payload->>'nickname', ''),
        nullif(after_payload->>'name', ''),
        nullif(before_payload->>'nickname', ''),
        nullif(before_payload->>'name', '')
      ),
      'group-' || entity_id_value
    );
  elsif tg_table_name = 'shared_addressbook_group_members' then
    before_key := 'beforeMember';
    after_key := 'afterMember';
    action_value := 'update_group_members';
    entity_type_value := 'group_members';
    entity_id_value := coalesce(after_payload->>'group_id', before_payload->>'group_id');
    entity_key_value := concat_ws(
      ':',
      'group_members',
      entity_id_value,
      coalesce(after_payload->>'contact_id', before_payload->>'contact_id')
    );
    select * into group_row
    from public.shared_addressbook_groups
    where id = entity_id_value;
    select * into contact_row
    from public.shared_addressbook_contacts
    where id = coalesce(after_payload->>'contact_id', before_payload->>'contact_id');
    display_name_value := nullif(btrim(group_row.name), '');
    entity_alias_value := public.outlook_exchange_alias(
      coalesce(nullif(group_row.nickname, ''), nullif(group_row.name, '')),
      'group-' || entity_id_value
    );
  else
    if tg_op = 'DELETE' then return old; end if;
    return new;
  end if;

  source_version_value := coalesce(
    nullif(after_payload->>'updated_at', '')::timestamptz,
    nullif(before_payload->>'updated_at', '')::timestamptz,
    clock_timestamp()
  );

  if change_set_id_value is not null then
    select logs.id into audit_log_id_value
    from public.audit_logs as logs
    where logs.table_schema = tg_table_schema
      and logs.table_name = tg_table_name
      and logs.operation = tg_op
      and logs.actor_id = audit_actor_id_value
      and logs.request_context->>'correlationId' = change_set_id_value::text
      and logs.record_pk = public.audit_row_pk(
        tg_table_schema,
        tg_table_name,
        coalesce(after_payload, before_payload)
      )
      and logs.before_row is not distinct from before_payload
      and logs.after_row is not distinct from after_payload
    order by logs.occurred_at desc, logs.id desc
    limit 1;
  end if;

  audit_log_ids_value := case
    when audit_log_id_value is null then array[]::uuid[]
    else array[audit_log_id_value]
  end;
  change_set_ids_value := case
    when change_set_id_value is null then array[]::uuid[]
    else array[change_set_id_value]
  end;
  operation_history := jsonb_build_array(tg_op);

  payload_value := jsonb_build_object(
    before_key, before_payload,
    after_key, after_payload,
    'group', case when group_row.id is null then null else to_jsonb(group_row) end,
    'contact', case when contact_row.id is null then null else to_jsonb(contact_row) end,
    'changedFields', to_jsonb(changed),
    'operationHistory', operation_history,
    'auditLogIds', to_jsonb(audit_log_ids_value),
    'changeSetIds', to_jsonb(change_set_ids_value),
    'userAuthorized', true
  );

  select queue.* into pending_queue
  from public.outlook_exchange_sync_queue as queue
  where queue.status = 'pending'
    and queue.entity_key = entity_key_value
    and queue.actor_id = actor_id_value
  order by queue.queue_sequence desc
  limit 1
  for update;

  if pending_queue.id is not null then
    earliest_before := case
      when pending_queue.payload ? before_key then pending_queue.payload -> before_key
      else before_payload
    end;
    changed := array_remove(
      public.audit_changed_fields(nullif(earliest_before, 'null'::jsonb), after_payload),
      'updated_at'
    );
    audit_log_ids_value := coalesce(pending_queue.audit_log_ids, array[]::uuid[]);
    if audit_log_id_value is not null and not audit_log_id_value = any(audit_log_ids_value) then
      audit_log_ids_value := array_append(audit_log_ids_value, audit_log_id_value);
    end if;
    change_set_ids_value := coalesce(pending_queue.change_set_ids, array[]::uuid[]);
    if change_set_id_value is not null and not change_set_id_value = any(change_set_ids_value) then
      change_set_ids_value := array_append(change_set_ids_value, change_set_id_value);
    end if;
    operation_history := coalesce(pending_queue.payload->'operationHistory', '[]'::jsonb) || jsonb_build_array(tg_op);

    if entity_type_value = 'contact' then
      action_value := case
        when (earliest_before is null or earliest_before = 'null'::jsonb) and after_payload is not null then 'create_contact'
        when after_payload is null then 'delete_contact'
        else 'update_contact'
      end;
    elsif entity_type_value = 'group' then
      action_value := case
        when (earliest_before is null or earliest_before = 'null'::jsonb) and after_payload is not null then 'create_group'
        when after_payload is null then 'delete_group'
        else 'update_group'
      end;
    end if;

    payload_value := payload_value || jsonb_build_object(
      before_key, earliest_before,
      after_key, after_payload,
      'changedFields', to_jsonb(changed),
      'operationHistory', operation_history,
      'auditLogIds', to_jsonb(audit_log_ids_value),
      'changeSetIds', to_jsonb(change_set_ids_value)
    );

    update public.outlook_exchange_sync_queue
    set action = action_value,
        entity_id = entity_id_value,
        entity_email = entity_email_value,
        entity_alias = entity_alias_value,
        display_name = display_name_value,
        payload = payload_value,
        requested_by = actor_name_value,
        audit_log_id = audit_log_id_value,
        audit_log_ids = audit_log_ids_value,
        change_set_id = change_set_id_value,
        change_set_ids = change_set_ids_value,
        changed_fields = changed,
        source_version = source_version_value,
        updated_at = clock_timestamp()
    where id = pending_queue.id
      and status = 'pending';
  else
    insert into public.outlook_exchange_sync_queue (
      action,
      entity_type,
      entity_id,
      entity_key,
      entity_email,
      entity_alias,
      display_name,
      payload,
      requested_by,
      actor_id,
      audit_log_id,
      audit_log_ids,
      change_set_id,
      change_set_ids,
      changed_fields,
      source_version
    ) values (
      action_value,
      entity_type_value,
      entity_id_value,
      entity_key_value,
      entity_email_value,
      entity_alias_value,
      display_name_value,
      payload_value,
      actor_name_value,
      actor_id_value,
      audit_log_id_value,
      audit_log_ids_value,
      change_set_id_value,
      change_set_ids_value,
      changed,
      source_version_value
    );
  end if;

  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

-- Repair existing derived counts before the updated_at trigger is installed.
update public.shared_addressbook_groups as groups
set member_count = counts.member_count
from (
  select groups_inner.id, count(members.contact_id)::integer as member_count
  from public.shared_addressbook_groups as groups_inner
  left join public.shared_addressbook_group_members as members
    on members.group_id = groups_inner.id
  group by groups_inner.id
) as counts
where groups.id = counts.id
  and groups.member_count is distinct from counts.member_count;

create or replace function public.outlook_addressbook_touch_updated_at()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  new.updated_at := clock_timestamp();
  return new;
end;
$$;

create or replace function public.outlook_addressbook_refresh_member_count()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  affected_group_id text;
begin
  for affected_group_id in
    select distinct group_id
    from (values
      (case when tg_op in ('UPDATE', 'DELETE') then old.group_id else null end),
      (case when tg_op in ('INSERT', 'UPDATE') then new.group_id else null end)
    ) as affected(group_id)
    where group_id is not null
  loop
    update public.shared_addressbook_groups as groups
    set member_count = counts.member_count
    from (
      select count(*)::integer as member_count
      from public.shared_addressbook_group_members as members
      where members.group_id = affected_group_id
    ) as counts
    where groups.id = affected_group_id
      and groups.member_count is distinct from counts.member_count;
  end loop;

  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

drop trigger if exists outlook_addressbook_touch_contact on public.shared_addressbook_contacts;
create trigger outlook_addressbook_touch_contact
  before update on public.shared_addressbook_contacts
  for each row execute function public.outlook_addressbook_touch_updated_at();

drop trigger if exists outlook_addressbook_touch_group on public.shared_addressbook_groups;
create trigger outlook_addressbook_touch_group
  before update on public.shared_addressbook_groups
  for each row execute function public.outlook_addressbook_touch_updated_at();

drop trigger if exists outlook_addressbook_touch_member on public.shared_addressbook_group_members;
create trigger outlook_addressbook_touch_member
  before update on public.shared_addressbook_group_members
  for each row execute function public.outlook_addressbook_touch_updated_at();

drop trigger if exists outlook_addressbook_member_count on public.shared_addressbook_group_members;
create trigger outlook_addressbook_member_count
  after insert or update or delete on public.shared_addressbook_group_members
  for each row execute function public.outlook_addressbook_refresh_member_count();

drop trigger if exists outlook_exchange_queue_contact on public.shared_addressbook_contacts;
create trigger outlook_exchange_queue_contact
  after insert or update or delete on public.shared_addressbook_contacts
  for each row execute function public.outlook_exchange_queue_source_change();

drop trigger if exists outlook_exchange_queue_group on public.shared_addressbook_groups;
create trigger outlook_exchange_queue_group
  after insert or update or delete on public.shared_addressbook_groups
  for each row execute function public.outlook_exchange_queue_source_change();

drop trigger if exists outlook_exchange_queue_member on public.shared_addressbook_group_members;
create trigger outlook_exchange_queue_member
  after insert or update or delete on public.shared_addressbook_group_members
  for each row execute function public.outlook_exchange_queue_source_change();

create or replace function public.claim_outlook_exchange_sync_queue(
  p_run_id uuid,
  p_limit integer default 200
)
returns setof public.outlook_exchange_sync_queue
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if p_run_id is null then raise exception 'p_run_id is required'; end if;

  return query
  with eligible as (
    select
      queue.id,
      row_number() over (
        partition by queue.entity_key
        order by queue.queue_sequence
      ) as entity_rank
    from public.outlook_exchange_sync_queue as queue
    where (
      queue.status = 'pending'
      or (
        queue.status = 'failed'
        and queue.attempts < 3
        and queue.next_attempt_at is not null
        and queue.next_attempt_at <= clock_timestamp()
      )
      or (
        queue.status = 'processing'
        and queue.attempts < 3
        and coalesce(queue.claimed_at, queue.processing_started_at, queue.updated_at, queue.created_at)
          < clock_timestamp() - interval '20 minutes'
      )
    )
    and not exists (
      select 1
      from public.outlook_exchange_sync_queue as active
      where active.entity_key = queue.entity_key
        and active.id <> queue.id
        and active.status = 'processing'
        and coalesce(active.claimed_at, active.processing_started_at, active.updated_at, active.created_at)
          >= clock_timestamp() - interval '20 minutes'
    )
  ), candidates as (
    select queue.id
    from public.outlook_exchange_sync_queue as queue
    join eligible on eligible.id = queue.id and eligible.entity_rank = 1
    where (
      queue.status = 'pending'
      or (
        queue.status = 'failed'
        and queue.attempts < 3
        and queue.next_attempt_at is not null
        and queue.next_attempt_at <= clock_timestamp()
      )
      or (
        queue.status = 'processing'
        and queue.attempts < 3
        and coalesce(queue.claimed_at, queue.processing_started_at, queue.updated_at, queue.created_at)
          < clock_timestamp() - interval '20 minutes'
      )
    )
    order by queue.queue_sequence
    for update of queue skip locked
    limit greatest(1, least(coalesce(p_limit, 200), 500))
  ), claimed as (
    update public.outlook_exchange_sync_queue as queue
    set status = 'processing',
        attempts = queue.attempts + 1,
        processing_started_at = clock_timestamp(),
        claimed_at = clock_timestamp(),
        completed_at = null,
        exchange_verified_at = null,
        error_message = null,
        run_id = p_run_id,
        updated_at = clock_timestamp()
    from candidates
    where queue.id = candidates.id
    returning queue.*
  )
  select * from claimed
  order by queue_sequence;
end;
$$;

create table if not exists public.outlook_exchange_sync_lock (
  lock_name text primary key,
  run_id uuid not null,
  sync_mode text not null,
  acquired_at timestamptz not null,
  heartbeat_at timestamptz not null,
  expires_at timestamptz not null
);

alter table public.outlook_exchange_sync_lock enable row level security;

create or replace function public.acquire_outlook_exchange_sync_lock(
  p_run_id uuid,
  p_sync_mode text,
  p_lease_minutes integer default 30
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  acquired boolean := false;
begin
  if p_run_id is null then raise exception 'p_run_id is required'; end if;
  insert into public.outlook_exchange_sync_lock (
    lock_name, run_id, sync_mode, acquired_at, heartbeat_at, expires_at
  ) values (
    'addressbook', p_run_id, coalesce(nullif(p_sync_mode, ''), 'incremental'),
    clock_timestamp(), clock_timestamp(),
    clock_timestamp() + make_interval(mins => greatest(5, least(coalesce(p_lease_minutes, 30), 180)))
  )
  on conflict (lock_name) do update
  set run_id = excluded.run_id,
      sync_mode = excluded.sync_mode,
      acquired_at = excluded.acquired_at,
      heartbeat_at = excluded.heartbeat_at,
      expires_at = excluded.expires_at
  where public.outlook_exchange_sync_lock.expires_at <= clock_timestamp()
     or public.outlook_exchange_sync_lock.run_id = excluded.run_id
  returning true into acquired;
  return coalesce(acquired, false);
end;
$$;

create or replace function public.renew_outlook_exchange_sync_lock(
  p_run_id uuid,
  p_lease_minutes integer default 30
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  renewed boolean := false;
begin
  update public.outlook_exchange_sync_lock
  set heartbeat_at = clock_timestamp(),
      expires_at = clock_timestamp() + make_interval(mins => greatest(5, least(coalesce(p_lease_minutes, 30), 180)))
  where lock_name = 'addressbook'
    and run_id = p_run_id
    and expires_at > clock_timestamp()
  returning true into renewed;
  return coalesce(renewed, false);
end;
$$;

create or replace function public.release_outlook_exchange_sync_lock(p_run_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  released boolean := false;
begin
  delete from public.outlook_exchange_sync_lock
  where lock_name = 'addressbook' and run_id = p_run_id
  returning true into released;
  return coalesce(released, false);
end;
$$;

drop policy if exists "shared_addressbook_contacts_write" on public.shared_addressbook_contacts;
drop policy if exists "shared_addressbook_groups_write" on public.shared_addressbook_groups;
drop policy if exists "shared_addressbook_group_members_write" on public.shared_addressbook_group_members;
drop policy if exists "outlook_exchange_sync_queue_write" on public.outlook_exchange_sync_queue;

revoke insert, update, delete on public.shared_addressbook_contacts from anon, authenticated;
revoke insert, update, delete on public.shared_addressbook_groups from anon, authenticated;
revoke insert, update, delete on public.shared_addressbook_group_members from anon, authenticated;
revoke insert, update, delete on public.outlook_exchange_sync_queue from anon, authenticated;
revoke all on public.outlook_exchange_sync_lock from public, anon, authenticated;

revoke all on function public.outlook_exchange_alias(text, text) from public, anon, authenticated;
revoke all on function public.outlook_exchange_queue_source_change() from public, anon, authenticated;
revoke all on function public.outlook_addressbook_touch_updated_at() from public, anon, authenticated;
revoke all on function public.outlook_addressbook_refresh_member_count() from public, anon, authenticated;
revoke all on function public.claim_outlook_exchange_sync_queue(uuid, integer) from public, anon, authenticated;
revoke all on function public.acquire_outlook_exchange_sync_lock(uuid, text, integer) from public, anon, authenticated;
revoke all on function public.renew_outlook_exchange_sync_lock(uuid, integer) from public, anon, authenticated;
revoke all on function public.release_outlook_exchange_sync_lock(uuid) from public, anon, authenticated;

grant execute on function public.claim_outlook_exchange_sync_queue(uuid, integer) to service_role;
grant execute on function public.acquire_outlook_exchange_sync_lock(uuid, text, integer) to service_role;
grant execute on function public.renew_outlook_exchange_sync_lock(uuid, integer) to service_role;
grant execute on function public.release_outlook_exchange_sync_lock(uuid) to service_role;
